name: ML

on: [workflow_dispatch, pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --privileged
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update dependencies
        run: apt-get update
      - name: Install utils
        run: apt-get install -y texlive-xetex pandoc
      - name: Install fonts
        run: |
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections
          apt-get install -y --reinstall ttf-mscorefonts-installer
          fc-cache -f
      - name: Setup repository
        uses: actions/checkout@v4
      - name: Build PDF
        run: |
          bash BuildLectures.sh
          bash BuildTheory.sh
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: ml
          path: |
            lectures/*.pdf
            theory/*.pdf
          if-no-files-found: error
          retention-days: 69
